REQUIRE, src/DataFramesMeta.jl, src/compositedataframe.jl, test/chaining.jl, test/compositedataframes.jl, test/dict.jl, test/speedtests.jl
Using 'call' as a variable name currently triggers a bug in
Julia 0.4: https://github.com/JuliaLang/julia/issues/11295
Work around it for now by using a different name.
Also get rid of deprecation warnings printed during the tests.
This PR currently breaks compatibility with 0.3. Should I use Compat.jl, or do you prefer creating a new branch for 0.4?
=> Fix tests and deprecation warnings

README.md, src/DataFramesMeta.jl, src/byrow.jl, test/dataframes.jl
This PR includes `@byrow`, a macro for working with DataFrame objects row-by-row. Includes `/src/byrow.jl`, an addition to `test/dataframes.jl` and an addition to `README.md`.
=> Add `@byrow`

README.md, src/DataFramesMeta.jl, test/dataframes.jl
Adds a feature to support column references as a variable. `@with(d, _I_(colref))` is the same as `d[colref]` (no colons there).
This is for #23. 
* Note that `@byrow!` doesn't support this feature. (There's no reason it couldn't be added.) It should work with the other macros like `@where`.
* The syntax is a little verbose. There might be punctuation available for this. Another option would be to embed the indicator in a symbol name. For example, `@with(d, :_I_colref)` is the same as `d[colref]`.
=> Add notation to support column references with a variable

src/DataFramesMeta.jl
It's undocumented (for now). Here's an example:
```julia
julia> d = DataFrame(a = P(rand(10)), b = P(1:10))
10x2 DataFrames.DataFrame
| Row | a         | b  |
|-----|-----------|----|
| 1   | 0.0775549 | 1  |
| 2   | 0.494738  | 2  |
| 3   | 0.0811539 | 3  |
| 4   | 0.508829  | 4  |
| 5   | 0.791939  | 5  |
| 6   | 0.775498  | 6  |
| 7   | 0.227743  | 7  |
| 8   | 0.612652  | 8  |
| 9   | 0.111757  | 9  |
| 10  | 0.550457  | 10 |
julia> dump(d)
DataFrames.DataFrame  10 observations of 2 variables
a: Array(Float64,(10,)) [0.07755486805429457,0.49473806399672116,0.0811539076123835,0.5088286373469713,0.7919390272672715,0.7754980486430811,0.22774251447406058,0.6126518937183227,0.11175723545500538,0.5504568184557108]
b: UnitRange{Int64} 
start: Int64 1
stop: Int64 10
```
=>  	Add PassThrough type to make it easier to use Arrays and NullableArrays

test/data.table.timings.jl
These benchmarks are from my favorite R package:
https://github.com/Rdatatable/data.table/wiki/Benchmarks-:-Grouping
We are way behind. All of the DataFrame grouping operations are at least 10X slower than data.table. On the plus side, the syntax compares favorably with either data.table or dplyr.
=> Add benchmarks from R's data.table benchmarks

README.md, src/byrow.jl, test/dataframes.jl
See #42 for background. Some notes:
* New columns don't get added to the original DataFrame, only the result.
* The syntax is based on the suggestion by @nalimilan:
```julia
df = DataFrame(A = 1:3, B = [2, 1, 2])
df2 = @byrow! df begin
@newcol colX::Array{Float64}
@newcol colY::DataArray{Int}
:colX = :B == 2 ? pi * :A : :B
if :A > 1 
:colY = :A * :B
end
end
```
=> Add @newcol feature to @byrow!

src/DataFramesMeta.jl, src/linqmacro.jl
In Julia 0.4.5 `depwarn()` is not exported, the Base module should be explicitly specified.
=> Fix depwarn() usage

README.md, src/compositedataframe.jl, test/cdftimings.jl, test/compositedataframes.jl
Includes:
*  `row(d,i)` and `eachrow(d, i)` for type-stable row access
* Named composite type creation
* More documentation
=> Improvements to CompositeDataFrames, including type-stable row access

src/DataFramesMeta.jl
Before, this yielded an error:
```julia
using DataFramesMeta: @where
using RDatasets: dataset
df = dataset("datasets", "iris")
@where df :Species .== "setosa"
```
=> Fixed `using DataFramesMeta: @where`

src/compositedataframe.jl
Two functions implemented the exact same signature `DataFrames.nrow(cdf::AbstractCompositeDataFrame)`. The last one (the effective one) will break if the `cdf` has 0 columns.
=> Duplicate definitions of DataFrames.nrow

.travis.yml, README.md, REQUIRE, appveyor.yml, src/DataFramesMeta.jl, src/byrow.jl, src/compositedataframe.jl, src/linqmacro.jl, test/chaining.jl, test/compositedataframes.jl, test/dataframes.jl, test/dict.jl, test/grouping.jl, test/linqmacro.jl, test/runtests.jl
Changes for 0.6, plus some very limited cleanups.
=> updates for 0.6

src/DataFramesMeta.jl
to avoid breaking the package on early 0.6-dev versions where `.&` did not work yet
=> use more specific VERSION cutoff for .& call

.travis.yml, README.md, REQUIRE, appveyor.yml, src/DataFramesMeta.jl, src/compositedataframe.jl, test/REQUIRE, test/compositedataframes.jl, test/data.table.timings.jl, test/dataframes.jl, test/dict.jl, test/grouping.jl
Also drop support for Julia 0.5 and NullableArrays.
=> DataFrames 0.11 support

src/DataFramesMeta.jl
A quickfix to reseolve #82. It calls an internal function of `DataFrames` for consistency but I assume we should allowed it here as it is a closely coupled package.
In general the reason for the problem was that we actually do not care about column names in this case.
=> fix depwarn in orderby

src/DataFramesMeta.jl
Calling `map()` over `keys(membernames)` returns a `Set`, which loses the ordering of columns and can make it inconsistent with `values(membernames)`.
Fixes https://github.com/JuliaStats/DataFramesMeta.jl/issues/88.
=> Fix incorrect ordering of columns with where and transform

REQUIRE, src/DataFramesMeta.jl, src/compositedataframe.jl, src/linqmacro.jl, test/cdftimings.jl, test/chaining.jl, test/compositedataframes.jl, test/data.table.timings.jl, test/dataframes.jl, test/dict.jl, test/grouping.jl, test/linqmacro.jl, test/runtests.jl, test/speedtests.jl, test/timings.jl
These are a bunch of simple fixes for 0.7.  There are still some outstanding problems.  In particular, wrong variables seem to get substituted in some cases.  It's almost as if DataFramesMeta is depending on ordering of `Expr` args somewhere where it shouldn't be, but it wasn't easy to find the problem (and I didn't).  This is a good first step at least.
=> various fixes for 0.7

README.md, src/DataFramesMeta.jl, test/dataframes.jl
`_I_` is a necessary and useful function in DataFramesMeta, but it is ugly to look at and difficult to read. 
This PR did a find and replace for `_I_` to `cols` across all files. 
Both `JuliaDBMeta` and `StatPlots` have the same escaping features, and both call their function `cols`. This PR makes `DataFramesMeta` more consistent with the rest of the ecosystem.
=> Rename _I_ to cols to be consistent with others

REQUIRE, src/DataFramesMeta.jl, test/grouping.jl
With this PR, now we allocate a vector using `reduce(v ...generator for all operations on groups...)` 
however I still have an error with type promotions. Consider the following example:
```
df = DataFrame(a = [1,2,3, missing, missing], b = [1,1,1,2,2])
g = groupby(df, :b)
@transform(g, x = mean(:a))
```
It seems like `reduce(append!, t(ig) for ig in g` should automatically promote types, but it doesn't.
=> Change the way grouped transforms work

REQUIRE, src/DataFramesMeta.jl
This should resolve https://github.com/JuliaData/DataFramesMeta.jl/issues/121.
In general I would also remove `DataFrame(::GroupedDataFrame)` method. If you feel it is useful let us add it to DataFrames.jl.
@nalimilan - any opinion?
=> Remove methods not belonging to DataFramesMeta.jl

README.md
`:z not defined in @select(df, x2 = 2 * :x, :y, :z)` example. Not useful for example anyways.
=> :z not defined in @select

README.md, src/byrow.jl, test/dataframes.jl
The `@byrow!` is simply duplicated and renamed to `@byrow` (also exported). The only difference is that one of them triggers the deprecation warning and the other does not. `@byrow!` documentation mention the deprecation and `@byrow` documentation just points to `@byrow!` documentation.
=> Deprecates `@byrow!` in favor of `@byrow`.

.github/workflows/TagBot.yml, test/dataframes.jl, test/grouping.jl
In preparation of using `DataFrames.transform` behind the scenes, I am writing a bunch of tests to 
1. Make sure we catch edge cases such as using reserved words 
2. Add `@test_throws` so we know exactly when we are adding new behavior or fixing current bugs. 
Please feel free to add tests as you see fit.
=> Improve tests for `@select` and `@transform`

README.md
=> Add warning to users about lack of support for `Not`, `Between`, and `All`

src/DataFramesMeta.jl, src/byrow.jl, test/dataframes.jl, test/grouping.jl
This is obviously inspired by [DataFramesMacros](https://github.com/matthieugomez/DataFramesMacros.jl) from @matthieugomez.
This PR introduces two macros, `@col` and `@row`. Here is the docstring introducting their behavior. 
@col(kw)
`@col` transforms an expression of the form `z = :x + :y` into it's equivalent in 
DataFrames's "mini-language". Functions act column-wise. For a row-wise functions, see 
`@row`
Parsing follows the same convention as other DataFramesMeta macros, such as `@with`. All 
terms in the expression that are `Symbols` are treated as columns in the DataFrame, except 
`Symbol`s wrapped in `^`. To use a variable representing a column name, wrap the variable 
in `cols`. 
`@col` constructs an anonymous function based off the given expression. It then creates
a `source => …
=> Make DataFrames piping functions the backend for @transform, @select, @by, and @based_on

README.md, src/DataFramesMeta.jl, src/byrow.jl, test/dataframes.jl, test/grouping.jl, test/linqmacro.jl
This will enable 
```
newname = :y 
df = DataFrame(x1 = [1], x2 = [2])
@transform(df, cols(newname) = :x1 + :x2)
```
This is a relatively uncontroversial and easy to implement feature! Tests will be added soon.
=> Allow cols on LHS

NEWS.md, News.md, src/DataFramesMeta.jl, test/grouping.jl
also add tests for `@select`, which already worked after #163 
Closes #176 and superscedes #178
=> Change `@transform` on a grouped dataframe to match DataFrames.transform

NEWS.md, README.md, src/DataFramesMeta.jl, test/byrow.jl, test/dataframes.jl, test/grouping.jl
Fixes #181 
This was an easy fix with easy tests to add. 
In the future this might get re-factored to allow for multiple column inputs in `cols`, but not today.
=> Fix mixing `Symbol`s and `String`s in `cols`

NEWS.md, Project.toml, README.md, src/DataFramesMeta.jl, test/dataframes.jl, test/grouping.jl, test/linqmacro.jl
Before, there was some complicated `with_anonymous` machinery. 
Now the backends are `select` and `combine`. 
For an abstract data frame this is intuitive, just call `select` on all the arguments with a `nolhs = true` option and return the `sortperm` from that. 
For a grouped data frame, unfortunately `@orderby` currently re-orders the groups and returns a grouped dataframe. 
This annoying because if you do, say, 
```
julia> df = DataFrame(a = [1, 1, 2, 2], b = [6, 6, 7, 7]);
julia> gd = groupby(df, :a);
julia> @orderby(df, :b)
```
then the result of the anonymous function in `@orderby` is a vector for each group and since Julia has lexicographic ordering of vectors, you can get some surprising results. 
~This was never tested and I'm not sure who uses it. I am making a breaking change …
=> Re-do the `@orderby` backend

README.md, docs/src/index.md, src/DataFramesMeta.jl, test/dataframes.jl
A very simple PR to add in-place macros in response to #215.
Suggestions welcomed.
=> add in-place macros @transform! and @select!

README.md
In reference to #218. We shouldn't update the readme to discuss `@select!` and `@transform!` until we make a new release. 
I would rather wait for a new release until we have `@subset` and `@subset!` and maybe and `@orderby!`. 
cc @nalimilan
=> delete @select! reference

docs/src/index.md
Another small chain, deleting the reference to Lazy's `@>` since it conflicts with `groupby`. Instead I discuss Chain.jl's `@chain` macro as an alternative to `@linq`.
=> delete @> reference, add chain

Project.toml
It seems there are some stragglers when it comes to updating re-export, see Blink.jl [here](https://github.com/JuliaGizmos/Blink.jl/issues/277). 
I recently tried to add FloatingTableView.jl with DataFramesMeta installed and it threw an incompatability. 
Better to be safe and re-allow the older versoin of Reexport.
=> re-add reexport 0.2

test/dataframes.jl
After https://github.com/JuliaData/DataFrames.jl/pull/2721, `transform!(df, :a => identity => :b)` will perform a copy. This is causing breaking tests.
=> Fix of === after DataFrames PR

Project.toml
Bumping to 0.7.0
I do this because we add new features, `@transform df begin ... end`, `@eachrow!`, and `@byrow` which are big enough changes to merit a new `0.x` given we are pre-1.0.
=> Bump to 0.7.0

Project.toml, src/DataFramesMeta.jl, src/parsing.jl, test/dataframes.jl
After #245, we have some `Base.remove_linenums!` scattered around. Initially I thought this was harmless, but it was not. See the following
```
julia> macro linenums_macro(arg)
if arg isa Expr && arg.head == :block && length(arg.args) == 1 && arg.args[1] isa LineNumberNode
esc(:(true))
else
esc(:(false))
end
end
@linenums_macro (macro with 1 method)
```
On master:
```
julia> df = DataFrame(a = [1], b = [2]);
julia> @transform(df, y = @linenums_macro begin end)
1×3 DataFrame
Row │ a      b      y     
│ Int64  Int64  Bool  
─────┼─────────────────────
1 │     1      2  false
```
On this branch
```
julia> @transform(df, y = @linenums_macro begin end)
1×3 DataFrame
Row │ a      b      y    
│ Int64  Int64  Bool 
─────┼────────────────────
1 │     1      2  true
```
Basically, macros inside …
=> Add dependency on MacroTools to avoid `Base.remove_linenums!`

Project.toml, docs/src/index.md, src/DataFramesMeta.jl, src/macros.jl, src/parsing.jl, test/astable.jl, test/dataframes.jl, test/grouping.jl, test/runtests.jl
This PR implements the following syntax
```
julia> df = DataFrame(a = [1, 2, 3], b = [4, 5, 6]);
julia> @transform df @astable (x = :a, y = :b)
3×4 DataFrame
Row │ a      b      x      y     
│ Int64  Int64  Int64  Int64 
─────┼────────────────────────────
1 │     1      4      1      4
2 │     2      5      2      5
3 │     3      6      3      6
```
It also re-configures the way we treat macro flags so it will be easier to generalize flags in the future. 
I still need to add docs and tests.
=> Re-factor macro-flag handling, fix Table-returning paths, only allow DataFrames 0.22 and above

docs/src/index.md, src/eachrow.jl, src/linqmacro.jl, src/macros.jl, src/parsing.jl, test/byrow.jl, test/chaining.jl, test/data.table.timings.jl, test/dataframes.jl, test/deprecated.jl, test/eachrow.jl, test/function_compilation.jl, test/grouping.jl, test/linqmacro.jl, test/performance.jl
In light of DataFrameMacros, this seems to be what people want. 
Benefits of `:y` on LHS
* More consistency, `QuoteNode`s *always* mean columns
* It's very hard to achieve that consistency without quoting everything, i.e. `y = f(x)` is hard to implement, and confuses scope. 
This will be a *major* PR in terms of updating tests and documentation. The actually change is very easy, so I will ping you when it's ready for a review.
=> `:y = f(:x)` instead of `y = f(:x)`

Project.toml
This version will  have 
* `@subset`
* `:y` on LHS instead of `:x`
* A small deprecation about `@combine` returning a table object.
=> Bump version to 0.8.0

docs/src/index.md, src/macros.jl
which mentions an unexported `@skipmissing`, which never got implemented.
Judging from 
https://github.com/pdeffebach/DataFramesMeta.jl/blob/8d55422f7f95fd8008fc895b54dc457506a19352/src/macros.jl#L428
and
https://github.com/pdeffebach/DataFramesMeta.jl/blob/8d55422f7f95fd8008fc895b54dc457506a19352/src/macros.jl#L436
added in https://github.com/JuliaData/DataFramesMeta.jl/pull/263, the `skipmissing` kwarg is set to `true` already by default when calling `@subset` and `@subset!`. So `@subset` appears to be a drop-in replacement for `@where` without having to do extra work.
=> Fix `@where` deprecation warning

docs/src/index.md, src/eachrow.jl, src/macros.jl, src/parsing.jl, test/astable.jl, test/byrow.jl, test/dataframes.jl, test/eachrow.jl, test/function_compilation.jl, test/grouping.jl, test/linqmacro.jl, test/subset.jl
With this PR, we no longer have `@transform df :y = f(cols("x"))`, but rather `@transform df :y = f($"x")`.
=> Cols to dollar

src/parsing.jl, test/byrow.jl
=> Fix bug disallowing `@rsubset(df, :a, :b, :c)`

docs/src/index.md, src/DataFramesMeta.jl, src/eachrow.jl, src/macros.jl
Rules: 
Inside `.md` files, you can use `$` however much you want. 
Inside docstrings, we have the global variable `const DOLLAR = raw"$"`. We interpolate `$DOLLAR` everywhere we want a raw `$`, which is ironic.
=> Fix escaping `$`

docs/src/index.md
You were correct, @bkamins , the rules are more complicated than I initially realized. So much that it's hard to put them all in a bulleted list. 
I think I have a good idea of the gaps and marked the appropriate places as unstable, and we can iteratively improve the code so the rules are clear and consistent.
=> Write up rules regarding multi-column indexing

Project.toml, src/DataFramesMeta.jl
This PR does 3 things
1. exports `@passmissing` for users to use the documentation, `? @passmissing` will work even if `@passmissing ...` won't outside of DataFramesMeta.jl macros
2. Only allows for DataFrames > 1.0, to fix #274 
3. Bump version to 0.9.0
We need to bump the version because we add new features and are pre-1.0.
=> Prepare for 0.9.0 release

.github/workflows/Documenter.yml, NEWS.md, Project.toml, docs/Project.toml, src/macros.jl, test/byrow.jl
Fixes #293 
@bkamins @nalimilan please review and merge!
Tests pass. This is a major oversight and needs to be fixed quickly. 
Thank you!
=> Add exclamations

src/eachrow.jl, src/macros.jl, src/parsing.jl, test/eachrow.jl, test/parsing.jl
This PR re-factors the expression handling. As a result it's now simpler, fewer LOC, and has more abstractions so the code is less fragile.
=> Refactor expression handling

Project.toml, docs/src/index.md, src/DataFramesMeta.jl, src/macros.jl, src/parsing.jl, src/parsing_astable.jl, test/astable_flag.jl, test/deprecated.jl, test/function_compilation.jl, test/grouping.jl, test/runtests.jl
This attempt should be a more robust strategy than the current `@t` flag in DataFrameMacros.jl. 
I will outline it in more detail shortly.
=> Another attempt at an astable flag

src/macros.jl
I was seeing the help for `@subset` in a Julia REPL and noticed that there is a missing space in the docstring.
=> Small docstring fix in src/macros.jl

docs/src/index.md, src/macros.jl, src/parsing.jl, test/astable_rhs.jl
After the recent improvements to `AsTable` in DataFrames, I guess it's time to make it easier to work with this construct in DataFramesMeta.jl. 
No tests added yet.
=> Allow AsTable on RHS in transformations

docs/src/index.md
I've fixed a few minor typos, see the tracked file.
=> Updated minor typos in index.md

src/parsing.jl, test/function_compilation.jl
This PR does *not* transform `f(g(:x))` to `(f ∘ g)(:x)`. 
Rather, it ensures that the expression
```
:y = (f ∘ g)(:a, :b)
```
gets turned into 
```
[:a, :b] => (f ∘ g ) => :y
```
which is a good first step for transforming `f(g(x))`. 
I'm leaving this undocumented for now, since it's a behind-the-scenes transformation.
=> Add support for f ∘ g 

src/parsing.jl, test/function_compilation.jl
This PR performs the following transformation
```
julia> DataFramesMeta.@col :y = first(last(:x))
[:x] => (first ∘ last => :y)
```
Tests are added and pass. I only need to fix one issue with macro hygiene, in case someone overloads `∘`.
=> Composition of nested functions

src/macros.jl
I added REPL jldoctest examples for the `@rselect` and `@rtransform` macros to demonstrate the easy syntax for operations that need a ByRow treatment.  
I choose these examples to show an easy way to post a value to a new column based on the row value in another column or combination of columns.
=> add ready examples to docstring for rselect, rtransform (#321)

NEWS.md, Project.toml
We should do a new release. The change from the last release was that now you can use `AsTable` on the RHS in #307
=> bump version to 0.11.0

src/eachrow.jl, test/eachrow.jl
Fixes #334 
Culprit was code from 0.6 which I believe is not needed.
=>  Fix eachrow bug #334

docs/Project.toml, docs/src/dplyr.md, src/macros.jl
Fixes https://github.com/JuliaData/DataFramesMeta.jl/issues/337
=> Replace `sortperm` by alternative pattern

docs/src/index.md, src/DataFramesMeta.jl, src/macros.jl, src/parsing.jl, test/dataframes.jl, test/grouping.jl, test/keyword_arguments.jl
This just adds keyword arguments for calls of the form `@subset(df, :a; view = true)`, rather than the multi-line version
```
@subset df begin 
:a 
end
```
I have added this for `@subset` but not others yet.
=> Allow for keyword arguments

NEWS.md, Project.toml
We've added two new features since the last release
* Added support for `Not`, `All`, and `Cols` in `@select`, making it easier to keep or drop many columns at once. ([#372](https://github.com/JuliaData/DataFramesMeta.jl/pull/372))
* Added the `@groupby` macro, which provides an easier syntax for grouping data frames ([#373](https://github.com/JuliaData/DataFramesMeta.jl/pull/373))
I always think I will wait until the next feature (metadata syntax, or `@when`) until the next release. But realistically we should keep a faster clip of releases. 
I put 0.15.0 as the release number because of the new features. We really need to get to 1.0. Which I think I will do after metadata is merged. 
@bkamins
=> Make a release for 0.15.0

Project.toml
As detailed on Slack
1. I tried to release 0.15.0. But then unknowingly messed it up by commenting in the Registry PR
2. I realized there was a bug in the documentation. So I hastily released a 0.15.1 rather than perform some hack about documentation. 
3. The 0.15.1 registry PR was blocked because I "skipped" 015.0. 
This gives me an opening to avoid the 0.15.1 release at all. I'm just going to re-set the version to 0.15.0 and then register that version.
=> Revert to version 15.0

src/macros.jl
just trying to help where I can
=> fix typo in @orderby docstring

docs/src/index.md
As a generalization, the highlights of DataFramesMeta.jl I have seen across the internet take unreadable DataFrames.jl syntax and make it readable with DataFramesMeta.jl, especially using multiple chained transformations. I think a better strategy is to take readable DataFrames.jl syntax and make it simple with DataFramesMeta.jl.
I cannot appreciate what DataFramesMeta.jl is doing if I cannot parse the Base DataFrames.jl syntax well enough to understand the goal, and the longer chained examples add to the feeling that DataFramesMeta.jl is more than most need. The package authors probably think the goal will be obvious by reading the DataFramesMeta.jl code, but since there are macros involved, the syntax could mean anything.
----
This instance is not particularly egregious. However, the …
=> Simplify index.md first example

Project.toml
Chain updated to v1.0 to indicate stability of API, with no braking changes to the API from v0.6 
See https://github.com/jkrumbiegel/Chain.jl/releases/tag/v1.0.0
This updates the compat bound on DataFramesMeta
Without the compat change the DataFramesMeta gets downgraded to v0.7.1 on my machine
=> Update Chain.jl Compat
