src/byrow.jl, test/dataframes.jl
Sorry, I don't think it worked last time. There is now an extra test for this functionality. I also added !'s.
=> Made byrow chainable (again)

.travis.yml, REQUIRE, src/compositedataframe.jl
Tests work now. Hopefully Travis will work.
=> [WIP] Attempt to fix tests and support travis

README.md, src/DataFramesMeta.jl, test/dataframes.jl
This is for the feature request in #13.
=> Support multiple arguments with @where (and-ed)

README.md, src/DataFramesMeta.jl, src/byrow.jl, src/linqmacro.jl, test/linqmacro.jl
=> Add docstrings, fix based_on, and update linq's where to support multiple args

README.md
I've updated the README to attempt to clarify package maintenance. This was spurred on by the discussion on julia-dev about package maintenance:
https://groups.google.com/forum/#!topic/julia-dev/vLalAXOhogg
=> Clarify package maintenance

.travis.yml, README.md, appveyor.yml, src/byrow.jl, src/compositedataframe.jl, test/data.table.timings.jl, test/linqmacro.jl
=> WIP: Get things working on Julia 0.5

src/DataFramesMeta.jl, test/dataframes.jl
Continuation of https://github.com/JuliaStats/DataFramesMeta.jl/pull/61, whose parent repository has been removed.
=> Some code cleaning

src/DataFramesMeta.jl, src/compositedataframe.jl, test/dataframes.jl, test/grouping.jl
is this needed to make things work here? If so, can that be refactored?
=> Remove type piracy on Base.select(::Associative)

README.md, src/linqmacro.jl, test/linqmacro.jl
A proposal of a solution to #94.
=> make linq accept qualified function names

README.md
I removed my name as lead maintainer. It was wishful thinking on my part that I'd have the dedication and time. Others have a more active role these days.
=> Update package maintenance section

src/DataFramesMeta.jl
Removes import of Compat in `src` and `test`.
=> Remove import of Compat

Project.toml, src/DataFramesMeta.jl, test/grouping.jl
=> Delete Tables.jl as a dependency

NEWS.md, src/DataFramesMeta.jl, test/dataframes.jl, test/grouping.jl
Consistent with the new backend of `@orderby` in #191 , I am writing a new backend for `@where`
1. Always returns a `DataFrame`
2. Makes a transformation by group and then filters
Need to add tests and write docs still.
=> Re-do the backend of `@where`

Project.toml, src/DataFramesMeta.jl, test/grouping.jl
Support for DataFrames 0.22
Supersedes #205
=> Zero 22 support

Project.toml
Breaking release, going from 0.5.1 to 0.6.0.
=> Bump version to 0.6.0

src/DataFramesMeta.jl, test/dataframes.jl
=> Cols select fix

Project.toml
=> reexport version bump

src/DataFramesMeta.jl
=> Add `sortperm` example in `@orderby` docstring

docs/src/index.md, src/macros.jl
@bkamins 
Made some small fixes to clarify what we mean by "keyword argument". Will merge after approval!
=> Improvements to keyword arguments documentation

NEWS.md
Add small change mentioning row-wise macros.
=> update news.md (#287)

docs/src/index.md
I've tested the examples given then added corrections where I thought there to be inconsistencies, as well as some changes to help the flow of the explanation.
=> Suggestions for Introduction 

docs/src/dplyr.md
... and reword slightly to read better (imo).
Thanks for DataFramesMeta!
=> Add a missing "add" in @transform section

docs/src/index.md
@pdeffebach - following https://discourse.julialang.org/t/confusing-misleading-error-message-for-a-beginner/91277/5 discusion
=> improve subsetting explanations

NEWS.md, Project.toml
@bkamins 
This is mostly for the bug fix that is popping up on Discourse
=> Update news and version for release 0.13

src/macros.jl, test/parsing.jl
Closes https://github.com/JuliaData/DataFramesMeta.jl/issues/369
=> fix a couple of typos

NEWS.md, Project.toml
=> Version bump 0.15.1

README.md
"Metaprogramming tools" sounds like it helps you write your own macros.
DataFramesMeta needs some help changing its initial impression: https://discourse.julialang.org/t/frustrated-using-dataframes/67833/4?u=nathan_boyer
=> Changed the README.md package description.
